version: "3.9"

services:
  {{SERVICE.SONAR_QUBE.NAME}}:
    image: library/sonarqube:10.1.0-community
    container_name: {{SERVICE.SONAR_QUBE.NAME}}
    hostname: {{SERVICE.SONAR_QUBE.NAME}}
    restart: always
    ports:
      - 0.0.0.0:{{SERVICE.SONAR_QUBE.PORTS.PORT_EXPOSED}}:9000
    networks:
      - {{SERVICE.SONAR_QUBE.NAME}}
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres.{{SERVICE.SONAR_QUBE.NAME}}:5432/postgres.{{SERVICE.SONAR_QUBE.NAME}}
      SONAR_JDBC_USERNAME: {{SERVICE.DATABASE.USER}}
      SONAR_JDBC_PASSWORD: {{SERVICE.DATABASE.PASSWORD}}
    volumes:
      - {{DIR.VOLUMES}}/{{SERVICE.SONAR_QUBE.NAME}}/Data:/opt/sonarqube/data
      - {{DIR.VOLUMES}}/{{SERVICE.SONAR_QUBE.NAME}}/Extensions:/opt/sonarqube/extensions
      - {{DIR.VOLUMES}}/{{SERVICE.SONAR_QUBE.NAME}}/Logs:/opt/sonarqube/logs
  postgres.{{SERVICE.SONAR_QUBE.NAME}}:
    image: library/postgres:13.3
    container_name: postgres.{{SERVICE.SONAR_QUBE.NAME}}
    hostname: postgres.{{SERVICE.SONAR_QUBE.NAME}}
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - {{SERVICE.SONAR_QUBE.NAME}}
    environment:
      POSTGRES_USER: {{SERVICE.DATABASE.USER}}
      POSTGRES_PASSWORD: {{SERVICE.DATABASE.PASSWORD}}
    volumes:
      - {{DIR.VOLUMES}}/postgres.{{SERVICE.SONAR_QUBE.NAME}}:/var/lib/postgresql
      - {{DIR.VOLUMES}}/postgres.{{SERVICE.SONAR_QUBE.NAME}}/Data:/var/lib/postgresql/data
networks:
  {{SERVICE.SONAR_QUBE.NAME}}:
    external: true



